# Generated by Django 3.0.3 on 2020-09-21 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='day_fin_sim',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='The month cannot be less or equal to 0'), django.core.validators.MaxValueValidator(32, message='This cannot be greater than 31')], verbose_name='Day in which the simulation ends'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='day_ini_sim',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='The day cannot be less or equal to 0'), django.core.validators.MaxValueValidator(32, message='The day cannot be greater than 31')], verbose_name='Day in which the simulation starts'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hourEND',
            field=models.IntegerField(verbose_name='Last hour with demand in the day'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hourINI',
            field=models.IntegerField(verbose_name='First hour with demand in the day'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='month_fin_sim',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='The month cannot be less or equal to 0'), django.core.validators.MaxValueValidator(13, message='The month cannot be greater than 12')], verbose_name='Month in which the simulation ends'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='month_ini_sim',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='The month cannot be less or equal to 0'), django.core.validators.MaxValueValidator(13, message='The month cannot be greater than 12')], verbose_name='Month in which the simulation starts'),
        ),
    ]
