# Generated by Django 3.0.3 on 2020-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0002_auto_20200921_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='hour_fin_sim',
            field=models.TimeField(verbose_name='Ending hour of simulation.'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hour_ini_sim',
            field=models.TimeField(verbose_name='Starting hour of simultation. For hourly simulations, day starts at 1 '),
        ),
    ]
