# Generated by Django 3.0.3 on 2020-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0002_simulation_itercontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='itercontrol',
            field=models.CharField(choices=[('paso_10min', 'ten-minutes steps'), ('paso_15min', 'fifteen-minutes steps'), ('horario', 'hourly steps')], max_length=10, verbose_name='Step control'),
        ),
    ]
