# Generated by Django 3.0.3 on 2020-09-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0004_auto_20200911_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteodata',
            name='min_sim',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='day_fin_sim',
            field=models.FloatField(default=1, verbose_name='Day in which the simulation ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='day_ini_sim',
            field=models.FloatField(default=1, verbose_name='Day in which the simulation starts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='hour_fin_sim',
            field=models.TimeField(default=0, verbose_name='Ending time of simulation. In case of hourly simulations: 1-24H, in case of ten-min or fifteen-min: 0-24H '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='hour_ini_sim',
            field=models.TimeField(default=0, verbose_name='Starting time of simultation. In case of hourly simulations: 1-24H, in case of ten-min or fifteen-min: 0-24H '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='month_fin_sim',
            field=models.FloatField(default=1, verbose_name='Month in which the simulation ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='month_ini_sim',
            field=models.FloatField(default=1, verbose_name='Month in which the simulation starts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hourEND',
            field=models.FloatField(verbose_name='Ending time of simulation'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='hourINI',
            field=models.FloatField(verbose_name='Starting time of simultation'),
        ),
    ]
