# Generated by Django 3.0.3 on 2020-11-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0004_simulation_annual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='annual',
            field=models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, verbose_name='¿Realizar simulación de un año completo?'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='huso',
            field=models.FloatField(verbose_name='Si se ha seleccionado que sí, escriba la diferencia horaria entre el formato del TMY y el formato UTC'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='itercontrol',
            field=models.CharField(choices=[('paso_10min', 'paso diezminutal'), ('paso_15min', 'paso quinceminutal'), ('horario', 'paso horario')], max_length=10, verbose_name='Paso de simulación'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='to_solartime',
            field=models.CharField(choices=[('on', 'Sí'), ('off', 'No')], max_length=3, verbose_name='¿Calcular hora solar?'),
        ),
    ]
