# Generated by Django 3.0.3 on 2020-11-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0005_auto_20201103_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='annual',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Do you want to simulate during a full year?'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='huso',
            field=models.FloatField(verbose_name='In case you have chosen to calclate solar time, write here the difference between the format of the TMY`s time and UTC'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='itercontrol',
            field=models.CharField(choices=[('paso_10min', '10 minutes'), ('paso_15min', '15 minutes'), ('horario', 'hourly steps')], max_length=10, verbose_name='Step of simulation'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='to_solartime',
            field=models.CharField(choices=[('on', 'Yes'), ('off', 'No')], max_length=3, verbose_name='Do you want to calculate the solar time?'),
        ),
    ]
