# Generated by Django 3.0.3 on 2020-11-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simforms', '0009_auto_20201103_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='hour_fin_sim',
            field=models.TimeField(verbose_name='Ending hour of simulation. For hourly simulations day starts at 1, so if you write 0, SHIPCal will not run'),
        ),
    ]
